version: 0.0
os: linux
files:
  - source: /
    destination: /home/www/flask_project
hooks:
  BeforeInstall:
    - location: scripts/cleanup_folder.sh
      runas: root
  ApplicationStart:
    - location: scripts/restart_supervisor.sh
      runas: root
      timeout: 60
