version: 0.0
os: linux
files:
  - source: /
    destination: /home/www/flask_project
hooks:
  BeforeInstall:
    - location: /opt/codedeploy-agent/deployment-root/$DEPLOYMENT_GROUP_ID/$DEPLOYMENT_ID/deployment-archive/scripts/cleanup_folder.sh
      runas: root
  ApplicationStart:
    - location: /opt/codedeploy-agent/deployment-root/$DEPLOYMENT_GROUP_ID/$DEPLOYMENT_ID/deployment-archive/scripts/restart_supervisor.sh
      runas: root
      timeout: 30
